language: python

python:
  - "3.6"

services:
  - mongodb

script:
  - py.test -rxs --cov mutacc/ tests/

jobs:
    include:
      - name: 'demo'
        script:
          - mutacc --demo extract --padding 100
          - mutacc --demo extract --padding 100 && mutacc --demo db import ./mutacc_demo_root/imports/demo_trio_import_mutacc.json
          - mutacc --demo db export --case-query '{}' --member child --proband --sample-name child
          - mutacc --demo synthesize --query ./mutacc_demo_root/queries/child_query_mutacc.json

before_install:
  - wget -q http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b -p /home/travis/miniconda
  - export PATH=/home/travis/miniconda/bin:$PATH
  - conda update --yes --quiet conda

install:

  - conda create -n mutacc_testenv --yes python=3.6 numpy cython
  - source activate mutacc_testenv
  - conda install --yes -c bioconda seqkit picard
  - pip install -r requirements.txt -r requirements-dev.txt -e .

notifications:
  email: false

after_success:
  - coveralls
