language: python

python:
  - "3.6"

services:
  - mongodb

script:
  - py.test tests/

before_install:

  - sudo apt-get install picard

install:
             
  - pip install cython
  - pip install -r requirements.txt
