version: '3'
# usage:
# (sudo) docker-compose up
# (sudo) docker-compose down
services:
  mongodb:
    image: mongo:4.4.9
    container_name: mongodb
    networks:
      - mutacc-net
    ports:
      - '27017:27017'
    expose:
      - '27017'

  # Service that extracts the reads from the case and saves them to database and exports results
  mutacc-demodata:
    build: .
    container_name: mutacc-demodata
    networks:
      - mutacc-net
    depends_on:
      - mongodb
    command: -c "
      mutacc --config-file mutacc/resources/config-demo.yml extract --picard-executable /home/worker/libs/picard.jar --padding 600 -c mutacc/resources/case.yaml &&
      mutacc --config-file mutacc/resources/config-demo.yml db import /home/worker/app/imports/demo_trio_import_mutacc.json &&
      mutacc --config-file mutacc/resources/config-demo.yml db export --all-variants --member child --proband --sample-name child &&
      mutacc --config-file mutacc/resources/config-demo.yml synthesize --query queries/child_query_mutacc.json --background-bam mutacc/resources/father.bam -f mutacc/resources/father_R1.fastq.gz -f2 mutacc/resources/father_R2.fastq.gz"
    volumes:
        - ./:/home/worker/app

networks:
  mutacc-net:
    driver: bridge
