version: "3"
services:
  mutacc:
    build: ../.
    links:
      - mutacc-db
    command: --version
    container_name: mutacc
    volumes:
      - /Users/adam.rosenbaum/mutacc_base/mutacc_root:/mutacc/mutacc_root


  mutacc-db:
    image: mongo
    hostname: mutacc-db
    ports:
      - 27030:27017
    volumes:
      - /Users/adam.rosenbaum/mutacc_base/mutacc_db:/data/db
    container_name: mutacc-db
    restart: always
