# Example of a demo config file.
# The following settings are used by docker-compose.yaml to create a demo instance of Mutacc
# But can be modified to provide custom params

uri: "mongodb://mongodb:27017/mutacc-test"
username: test_user
password: test_pw
database: mutacc-test
root_dir: /home/worker/app
binaries:
  seqkit: "../libs/seqkit"
  picard: "../libs/picard.jar"
