name: Run an integration test
on: [pull_request]
jobs:
  integration_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Conda and install python 3.8
        uses: s-weigand/setup-conda@v1
        with:
          activate-conda: true
          python-version: 3.8
      - run: conda install --yes -c bioconda seqkit picard

      - name: Install repo and its dependencies
        run: |
          pip install -r requirements.txt
          pip install -e .

      - name: Integration test
        script:
          - mutacc --demo extract --padding 100
          - mutacc --demo db import ./mutacc_demo_root/imports/demo_trio_import_mutacc.json
          - mutacc --demo db export --all-variants --member child --proband --sample-name child
          - mutacc --demo synthesize --query ./mutacc_demo_root/queries/child_query_mutacc.json
