# This test is making sure all commands work
# by running the repo docker-compose file and checking that outfiles are created

name: Integration tests
on: [pull_request]
jobs:
  integration_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Start and run containers
        run: |
          docker-compose up -d
          [ ! -f datasets/synthetic_child_father_R1.fastq.gz ] && exit 1

      - name: Stop containers
        run: docker-compose down
