name: Integration tests
on: [pull_request]
jobs:
  integration_test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        mongodb-version: ['7']

    steps:
      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1
        with:
          mongodb-version: ${{ matrix.mongodb-version }}

      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Conda and install python
        uses: s-weigand/setup-conda@v1
        with:
          activate-conda: true
          python-version: 3.11
      - run: conda install --yes -c bioconda seqkit picard

      - name: Install repo and its dependencies
        run: |
          pip install -r requirements.txt
          pip install -e .

      - name: Test run pipeline
        run: |
          mutacc --root-dir . extract --picard-executable picard.jar --padding 600 -c mutacc/resources/case.yaml
          mutacc --root-dir . db import imports/demo_trio_import_mutacc.json
          mutacc --root-dir . db export --all-variants --member child --proband --sample-name child