# This test is making sure all commands work
# by running the repo docker-compose file and checking that outfiles are created

name: Integration tests
on: [pull_request]
jobs:
  integration_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Start containers
        run: docker-compose up -d

      - name: Check oufiles existence
        id: check_files
        uses: andstor/file-existence-action@v1
        with:
          files: "datasets/synthetic_child_father_R1.fastq.gz, datasets/synthetic_child_father_R2.fastq.gz"
          allow_failure: false

      - name: Stop containers
        run: docker-compose down
